// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCGaSF-iyfvV_eZYuAO4z4mCcU3FKCOE',
    appId: '1:935594574887:web:957119d9157fefa9bbfa02',
    messagingSenderId: '935594574887',
    projectId: 'fir-hub-2a6bf',
    authDomain: 'fir-hub-2a6bf.firebaseapp.com',
    storageBucket: 'fir-hub-2a6bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6Mxomr0IeYepD6WoLSa5vGpCZ9r3ygU',
    appId: '1:935594574887:android:99304b9bd2c35a68bbfa02',
    messagingSenderId: '935594574887',
    projectId: 'fir-hub-2a6bf',
    storageBucket: 'fir-hub-2a6bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvraAfabLqzasFOx0O15vdM7KJxevwOVs',
    appId: '1:935594574887:ios:a134c842fcc09bf1bbfa02',
    messagingSenderId: '935594574887',
    projectId: 'fir-hub-2a6bf',
    storageBucket: 'fir-hub-2a6bf.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvraAfabLqzasFOx0O15vdM7KJxevwOVs',
    appId: '1:935594574887:ios:a134c842fcc09bf1bbfa02',
    messagingSenderId: '935594574887',
    projectId: 'fir-hub-2a6bf',
    storageBucket: 'fir-hub-2a6bf.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );
}
